### ISSUE TITLE
Issue with compatability with the Func_Godot plugin

### ISSUE THREAD

**Issue by youporkchop5** [Zorochase/ultimate-retro-shader-collection#1]
Hi there,

I've been trying to get use out of these shaders by applying them to the entirety of my game world, which has been generated with [Func_Godot](https://github.com/func-godot). It's a plugin that lets me design levels inside a level design program like Trenchbroom and import them into Godot. It auto-generates BaseMaterial3Ds to use based on the same textures inside Trenchbroom, with the albedo of the generated materials matching the texture (though you can also set it up to generate ShaderMaterials). 

I've been trying to replace these materials/get it to auto-generate ShaderMaterials using the standard-opaque shader provided inside this pack. However, it simply doesn't work. The texture appears to stretch across everything it's applied to.

Normal, using auto-generated BaseMaterial3Ds
![image](https://github.com/Zorochase/ultimate-retro-shader-collection/assets/52052551/4980ffae-f598-4a1d-8338-e5dea358986c)

Broken, after conversion to ShaderMaterials using the provided shaders.
![image](https://github.com/Zorochase/ultimate-retro-shader-collection/assets/52052551/72c1986b-4d01-413b-b204-144156010d1d)

I can change the albedo of the normal BaseMaterial3Ds to a different texture inside my texture pack.
![image](https://github.com/Zorochase/ultimate-retro-shader-collection/assets/52052551/c7e5b468-ec4a-4f5b-aed2-c12fb2d0743f)

And I can change the albedo of the cube provided in the demo to showcase the shaders, and it'll be fine.
![image](https://github.com/Zorochase/ultimate-retro-shader-collection/assets/52052551/a93f1e77-4506-4a29-8660-6633c4f50bf9)
![image](https://github.com/Zorochase/ultimate-retro-shader-collection/assets/52052551/c9b99b8c-1cbf-46c8-b945-22898af1a6f7)

There's no issue with converting the BaseMaterial3Ds to ShaderMaterials using Godot's built in converter.
There's also no issue with the functionality of the shaders beside the albedo. The vertex shifting and other effects occur correctly.

This issue only crops up when I change the albedo of the generated Func_Godot meshes into ShaderMaterials using the provided shaders. I've also asked about the issue to the members of the Func_Godot team, who recommended I ask here about it. Could you please help explain what the cause of the issue might be? Admittedly, I don't altogether understand how shaders function. Any insight you could give that would help me use these with my game would be great, because I do think the shaders look really great.

**Comment by Zorochase** [comment]
> The texture appears to stretch across everything it's applied to.

This is due to a lack of subdivision. The less subdivided a mesh is, the more noticeable affine texture mapping (texture warping/stretching) will be. If there's a way you can subdivide your map's meshes, either through some option in Func_Godot or your mapmaking tool, this should fix it. I have no experience with Func_Godot or Quake mapmaking so I unfortunately couldn't tell you how. If you can't, you may need to disable this effect (though the others should still work).

**Comment by youporkchop5** [comment]
I should've mentioned this, its my bad. I disabled affine texture mapping earlier and it didn't seem to fix the issue.

**Comment by Zorochase** [comment]
Did you enable texture repeat as I mentioned in the other comment? Also, would you be able to upload a test project with the maps in your screenshot? It's hard to tell what else might be wrong just from the screenshots and issue description.

**Comment by youporkchop5** [comment]
Hey so, it completely started to work once I applied `#define TEXTURE_REPEAT` to the top of `common.gdshaderinc`. Would you still like me to upload a test project so you can take a look at why it was happening?

**Comment by Zorochase** [comment]
No thanks, that won't be necessary. I'm glad you've got it working!
